### ISSUE TITLE
AMF and SMF stuck checking in wait-nrf.

### ISSUE THREAD

**Issue by ajgillette** [free5gc/free5gc-helm#4]
I did a helm install of the latest free5gc and The AMF and SMF never go ready. When I investigated I found that those two pods are waiting for the nrf. Other pods detect that the nerf is up and continue to ready but the SMF and AMF do not. I exec'd into the mongoldb pod because it has curl. I do the following and I get a response:

$ curl -X PUT http://nrf-nnrf:8000/nnrf-nfm/v1/nf-instances/d9785fd4-08be-4e85-97af-7928f1846b9d
{"title":"Malformed request syntax","status":400,"detail":"[Request Body] unexpected end of JSON input"}$

I can't do the same command from inside the AMF or SMF because they don't have curl. I disabled the wait-nerf container and now
I see this in the SMF log:

2024-05-17T18:49:52.654160895Z [INFO][SMF][Consumer] SMF register to NRF Error[Put "http://nrf-nnrf:8000/nnrf-nfm/v1/nf-instances/d9785fd4-08be-4e85-97af-7928f1846b9d": dial tcp: lookup nrf-nnrf on 10.96.0.10:53: read udp 192.168.154.36:45638->10.96.0.10:53: i/o timeout]

**Comment by ianchen0119** [comment]
@lyz508 please help to check, tks!

**Comment by lyz508** [comment]
Hi @ajgillette,

Could you please provide the environment details, the logs of NRF/SMF/AMF, and the steps you followed to perform the Helm Chart installation?

Alternatively, if you want to test whether the NRF is ready, you can try the following command and check whether the return code of the GET request is 200:
```
curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" http://nrf-nnrf:8000/
```

**Comment by ajgillette** [comment]
The logs from the SMF, AMF say that the registration timed out but the NRF is reachable from all the other pods. The issue is the network connection. I keep asking myself how the services can be running, sending and receiving packets but not able to reach the other services? VPNs perhaps? IPTables rules or some other NAT?How can a pod look connected to the cluster network but not be connected?..FG..Sent from my iPhone14On May 26, 2024, at 4:55 AM, linyz ***@***.***> wrote:﻿
Hi @ajgillette,
Could you please provide the environment details, the logs of NRF/SMF/AMF, and the steps you followed to perform the Helm Chart installation?
Alternatively, if you want to test whether the NRF is ready, you can try the following command and check whether the return code of the GET request is 200:
curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" http://nrf-nnrf:8000/

**Comment by ajgillette** [comment]
I’ll send the helm command and logs tomorrow...FG..Sent from my iPhone14On May 26, 2024, at 4:55 AM, linyz ***@***.***> wrote:﻿
Hi @ajgillette,
Could you please provide the environment details, the logs of NRF/SMF/AMF, and the steps you followed to perform the Helm Chart installation?
Alternatively, if you want to test whether the NRF is ready, you can try the following command and check whether the return code of the GET request is 200:
curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" http://nrf-nnrf:8000/

**Comment by lyz508** [comment]
Hi @ajgillette,

I wanted to follow up and ask if there have been any updates or new information.

Regards,
